const BUBBLES_DATA = [
    {
        title: 'BRANDSCHUTZ',
        link: '/brandschutz',
        delay: .5,
        customClass: 'red',
        left: '0px',
        top: '0px',
        color: '#fb503cb3',
    },
    {
        title: 'TGA',
        link: '/technische',
        top: '0px',
        delay: .9,
        customClass: 'blue',
        right: '2rem',
        color: '#4159cab3',
    },
    {
        title: 'PROJEKTENTWICKLUNG',
        link: '/projektentwicklung',
        left: '650px',
        top: '285px',
        delay: 1.3,
        customClass: 'yellow',
        color: '#ffea41b3',
    },
    {
        title: 'ENERGIEBERATUNG',
        link: '/energieberatung',
        top: '-50px',
        delay: 1.7,
        customClass: 'green',
        right: '22rem',
        color: '#27c97db3',
    },
    {
        title: 'ARCHITEKTUR',
        link: '/architektur',
        left: '18rem',
        top: '-15px',
        delay: 2.1,
        customClass: 'silver',
        color: '#89adcdb3',
    },
    {
        title: 'FINANZIERUNG',
        link: '/finanzierung',
        left: '975px',
        top: '275px',
        delay: 2.5,
        customClass: 'orange',
        color: '#fa8d56b3',
    },
    {
        title: 'STATIK',
        link: '/tragwerksplanung',
        left: '50px',
        top: '250px',
        delay: 2.9,
        customClass: 'purple',
        color: '#ba69afb3',
    },
    {
        title: 'BAUANTRAG',
        link: '/bauantrag',
        left: '370px',
        top: '370px',
        delay: 3.2,
        customClass: 'dark-green',
        color: '#215c38b0',
    }
]

export { BUBBLES_DATA }