import Head from 'next/head';
import Slick from '../components/commons/Slick';
import Button from '../components/commons/homeButton';
import Footer from '../components/footer';
import Header from '../components/header';
import { Metadata } from 'next';
import BlogWrapper from '../components/blog';
import { Blog } from '../types';
import getAllBlogs from '../api/getAllBlogs';

export const metadata: Metadata = {
    title: 'SPEKTRUM | Architekten Ingenieure',
    description: 'Architekten, Generalplaner',
}

export default async function Home() {

  const blogsData: Blog[] = await getAllBlogs();

  return (
    <div>
      <Head>
        <title>SPEKTRUM - Architekten Ingenieure</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button />
        <Header isHomePage />
        <Slick />
        <BlogWrapper blogsData={blogsData} />
        <Footer />
      </main>

      <footer>
      </footer>
    </div>
  )
}
