import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner'
import Slick from '../components/commons/Slick'
import Caraousel from '../components/commons/carousel/Carousel'
import Button from '../components/commons/homeButton'
import Footer from '../components/footer'
import Header from '../components/header'
//Motion framer


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button />
        <Header />
        <Slick />
        <Caraousel />
        <Footer />
      </main>

      <footer>
      </footer>
    </div>
  )
}
